# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 833b51fa596bddc9cd66c674ed4ff5a325bd854fe755bf8311d3191f75ea5ed7feb63242f671cf5b1e9ceac5ff86afb16ca8e19ca1283571f224c293d7ba3a5f

test:
  secret_key_base: e27668518dbf102926a0c9407325af8a053cd67ec865f94456402307afc192c54ffb6b4712e71ba876c813977f948afdc46f8ce4613b01159f7815002266e809

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
